import type { Metadata } from "next";
import { ModalProvider } from "@/components/common/modal";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/MonadABXY/mona-font/web/mona.css"
        />
      </head>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <ModalProvider>{children}</ModalProvider>
      </body>
    </html>
  );
}
